---
rhos_release: 17
hostname: standalone
clouddomain: shiftstack
control_plane_cidr: 192.168.24.0/24
public_cidr: 192.168.25.0/24

cirros_url: http://download.cirros-cloud.net/0.5.1/cirros-0.5.1-x86_64-disk.img
rhcos_meta_url: https://raw.githubusercontent.com/openshift/installer/master/data/data/rhcos.json
# Define rhcos_url to override use of rhcos_meta_url
