---
- hosts: standalone
  become: true
  become_user: root
  gather_facts: false
  vars_files: vars/defaults.yaml

  tasks:
    #  - debug:
    #      msg: "{{ cidr }}"
    #    vars:
    #      cidr: "{{ control_plane_cidr | nthhost(1) }}/{{ control_plane_cidr | ipaddr('prefix') }}"
    #
    #  - fail:
    #      msg: blah

  - name: install rhos-release
    yum:
      state: installed
      name: 
      - http://download.devel.redhat.com/rcm-guest/puddles/OpenStack/rhos-release/rhos-release-latest.noarch.rpm
      disable_gpg_check: True

  - name: Configure rhos release "{{ rhos_release }}"
    shell: rhos-release "{{ rhos_release }}"

  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: Set hostname to "{{ hostname }}"
    hostname:
      name: "{{ hostname }}"

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Create the stack user
    user:
      name: stack
      groups: wheel

  - name: Copy the script for creating dummy interfaces 
    copy:
      src: "files/create_if"
      dest: "/usr/local/bin/"
      owner: root
      group: root
      mode: '0755'

  - name: Create systemd units for dummy interfaces
    template:
      src: "dummy.service.j2"
      dest: "/etc/systemd/system/{{ item.name }}.service"
      owner: root
      group: root
      mode: '0644'
    vars:
      interface_name: "{{ item.name }}"
      interface_cidr: "{{ item.cidr }}"
    loop:
    - name: dummy0
      cidr: "{{ control_plane_cidr | nthhost(1) }}/{{ control_plane_cidr | ipaddr('prefix') }}"
    - name: dummy1
      cidr: "{{ public_cidr | nthhost(1) }}/{{ public_cidr | ipaddr('prefix') }}"

  - name: Activate the systemd units for dummy interfaces
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
      daemon_reload: yes
    loop:
    - dummy0.service
    - dummy1.service

  - name: Fetch the Red Hat root certificate
    get_url:
      dest: /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
      url: https://password.corp.redhat.com/RH-IT-Root-CA.crt

  - name: Add the certificate to the local trust bundle
    shell: |
      update-ca-trust enable
      update-ca-trust extract

  - name: Install the tripleo client
    yum:
      name:
      - python3-tripleoclient
